"""
Evolved Feature Engineering — Discovered by ShinkaEvolve (Agent Loop)

Auto-generated by agent loop. Features evolved through continuous improvement.
"""

import numpy as np
import pandas as pd


def engineer_evolved_features(df):
    """
    Create interaction features from the base transaction columns.

    Available numeric columns (after leaky feature removal):
      amount_jpy, amount_log, receiver_account_age_days,
      sender_account_age_days, sender_ib_days_since_enabled,
      txn_count_24h, txn_volume_24h, amount_zscore, hour

    Available binary columns:
      is_high_amount, is_very_high_amount, first_transfer,
      sender_ib_enabled, sender_suspicious_device,
      receiver_is_new, receiver_is_very_new, has_recent_activity,
      amount_above_mean, amount_much_above_mean,
      is_weekend, is_business_hours, is_late_night

    Returns a DataFrame with new feature columns only.
    """
    feats = pd.DataFrame(index=df.index)

    # IB enablement ratio: how recently IB was enabled relative to account age
    feats['ib_age_ratio'] = df['sender_ib_days_since_enabled'].fillna(9999) / (df['sender_account_age_days'] + 1)
    
    # Velocity intensity: volume per transaction in recent window
    feats['avg_recent_txn_amount'] = df['txn_volume_24h'] / (df['txn_count_24h'] + 1)

    # New account interaction with high amount and suspicious device flag
    feats['new_acct_high_amount_suspicious'] = (df['receiver_is_new'].fillna(0) * 
                                                 np.where((df['amount_jpy'] > 50000), 1, 0)) * \
                                                df['sender_suspicious_device']

    # Suspicious device interaction with weekend high volume
    feats['suspicious_weekend_high_volume'] = (df['sender_suspicious_device'].fillna(0) *
                                                np.where(df['is_weekend'], df['txn_count_24h'], 0))

    # First transfer to new receiver with high amount and suspicious device
    feats['first_txn_new_receiver_high_amount_suspicious'] = (df['first_transfer'].fillna(0) * 
                                                               (df['receiver_is_new'].fillna(0) + 
                                                                np.where((df['is_high_amount'].fillna(0)), 1, 0)) *
                                                              df['sender_suspicious_device'])

    # High velocity interaction with high amount
    feats['high_velocity_high_amount'] = (np.where(df['txn_count_24h'] > 5, 1, 0) *
                                          np.where((df['amount_jpy'] > 50000), 1, 0))
    
    # Interaction between suspicious device and high amount
    feats['suspicious_high_amount'] = (np.log(df['amount_jpy']) *
                                        df['sender_suspicious_device'].fillna(0))

    return feats


def get_evolved_feature_columns():
    """Return list of evolved feature column names."""
    return [
        'ib_age_ratio',
        'avg_recent_txn_amount',
        'new_acct_high_amount_suspicious',
        'suspicious_weekend_high_volume',
        'first_txn_new_receiver_high_amount_suspicious',
        'high_velocity_high_amount',
        'suspicious_high_amount'
    ]
