"""
Code Integrator for Agent Loop

Extracts evolved features from best program and updates production code.
"""

import re
import subprocess
import sys
from pathlib import Path
from typing import Tuple


def extract_evolved_features_function(best_program_path: Path) -> str:
    """
    Extract the engineer_evolved_features function from best evolved program.

    Args:
        best_program_path: Path to the best evolved program (main.py)

    Returns:
        String containing the function code (including def line)

    Raises:
        ValueError: If function not found
    """
    with open(best_program_path, 'r') as f:
        program_code = f.read()

    # Look for EVOLVE-BLOCK markers around engineer_evolved_features
    pattern = (
        r'# EVOLVE-BLOCK-START\s+def engineer_evolved_features\(.*?\):\s+""".*?"""'
        r'(.*?)'
        r'# EVOLVE-BLOCK-END'
    )

    match = re.search(pattern, program_code, re.DOTALL)
    if match:
        # Extract the whole function with def line
        func_start = program_code.find('def engineer_evolved_features')
        func_block_end = program_code.find('# EVOLVE-BLOCK-END', func_start)
        if func_start != -1 and func_block_end != -1:
            func_code = program_code[func_start:func_block_end].strip()
            return func_code

    # Fallback: find function without EVOLVE-BLOCK markers
    pattern_simple = (
        r'def engineer_evolved_features\(.*?\):\s+""".*?""".*?\n(?:    .*\n)*?'
        r'(?=\n(?:def |# EVOLVE-BLOCK|$))'
    )
    match = re.search(pattern_simple, program_code, re.DOTALL)
    if match:
        return match.group(0).strip()

    raise ValueError(f"Could not extract engineer_evolved_features from {best_program_path}")


def extract_model_params_function(best_program_path: Path) -> str:
    """
    Extract the get_model_params function from best evolved program (if present).

    Args:
        best_program_path: Path to the best evolved program

    Returns:
        String containing the function code, or empty string if not found
    """
    with open(best_program_path, 'r') as f:
        program_code = f.read()

    pattern = r'def get_model_params\(\):.*?\n(?:    .*\n)*?(?=\n(?:def |# |$))'
    match = re.search(pattern, program_code, re.DOTALL)

    if match:
        return match.group(0).strip()
    return ""


def update_evolved_features_file(
    evolved_features_function: str,
    output_path: str = "src/features/evolved_features.py"
) -> None:
    """
    Update the evolved_features.py file with new evolved features.

    Args:
        evolved_features_function: String containing the function code
        output_path: Path to evolved_features.py to update
    """
    # Extract column names from assignments like feats['col_name'] = ...
    col_names = re.findall(r"feats\['(\w+)'\]\s*=", evolved_features_function)
    col_list_str = ",\n        ".join(f"'{c}'" for c in col_names)

    template = f'''"""
Evolved Feature Engineering — Discovered by ShinkaEvolve (Agent Loop)

Auto-generated by agent loop. Features evolved through continuous improvement.
"""

import numpy as np
import pandas as pd


{evolved_features_function}


def get_evolved_feature_columns():
    """Return list of evolved feature column names."""
    return [
        {col_list_str}
    ]
'''

    with open(output_path, 'w') as f:
        f.write(template)

    print(f"  ✓ Updated {output_path}")


def retrain_models() -> None:
    """
    Retrain models with updated evolved features.

    This runs the full training pipeline with the new features.
    """
    project_root = Path(__file__).parent.parent.parent

    print(f"  🏋️  Retraining models with new features...")

    # Retrain account risk model
    cmd = [
        sys.executable,
        str(project_root / "src" / "models" / "account_risk_model.py"),
    ]
    try:
        subprocess.run(cmd, cwd=str(project_root), check=True, capture_output=True)
        print(f"     ✓ Account risk model retrained")
    except subprocess.CalledProcessError as e:
        print(f"     ⚠ Account risk model retrain failed: {e}")

    # Retrain transfer risk model
    cmd = [
        sys.executable,
        str(project_root / "src" / "models" / "transfer_risk_model.py"),
    ]
    try:
        subprocess.run(cmd, cwd=str(project_root), check=True, capture_output=True)
        print(f"     ✓ Transfer risk model retrained")
    except subprocess.CalledProcessError as e:
        print(f"     ⚠ Transfer risk model retrain failed: {e}")

    print(f"     ✓ Models retrained")


def validate_extracted_function(function_code: str) -> Tuple[bool, str]:
    """
    Validate that extracted function is valid Python.

    Args:
        function_code: String containing the function code

    Returns:
        Tuple of (is_valid: bool, error_message: str)
    """
    try:
        compile(function_code, '<extracted_function>', 'exec')
        return True, ""
    except SyntaxError as e:
        return False, str(e)
